# Generated by Django 3.1.6 on 2021-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listvehicle', '0004_agents'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
