# Generated by Django 3.1.6 on 2021-03-16 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listvehicle', '0005_agents_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='timestamp',
        ),
    ]
